pipeline {
    agent any

    environment {
        MAVEN_HOME = tool 'Maven 3.6.3' // Use the name specified in the Maven configuration
        SONARQUBE_URL = 'http://3.110.221.139:9000/'
        SONARQUBE_TOKEN = 'sqa_e2e0dae9d7a2c5d12338834474b5932dee3c2805'
        NEXUS_URL = 'http://13.201.93.14:8081/repository/maven-releases/' // Ensure no double slashes
        NEXUS_CREDENTIALS_ID = 'my-nexus-credentils' // Use the credentials ID
        TOMCAT_URL = 'http://3.110.204.118:8080/manager/text' // Use /text for curl deployment
        TOMCAT_CREDENTIALS_ID = 'my-tomcat-credentials' // Use the credentials ID
    }

    stages {
        stage('Check curl Version') {
            steps {
                sh 'curl --version'
            }
        }

        stage('Checkout') {
            steps {
                git 'https://github.com/saipurandhar1234/Hello-World.git'
            }
        }

        stage('Build') {
            steps {
                sh "${MAVEN_HOME}/bin/mvn clean install"
            }
        }

        stage('SonarQube Analysis') {
            steps {
                sh """
                    ${MAVEN_HOME}/bin/mvn sonar:sonar \
                    -Dsonar.host.url=${SONARQUBE_URL} \
                    -Dsonar.login=${SONARQUBE_TOKEN}
                """
            }
        }

        stage('Upload to Nexus') {
            steps {
                // Using credentials for Nexus
                withCredentials([usernamePassword(credentialsId: NEXUS_CREDENTIALS_ID, usernameVariable: 'NEXUS_USERNAME', passwordVariable: 'NEXUS_PASSWORD')]) {
                    sh """
                        curl -v --user $NEXUS_USERNAME:$NEXUS_PASSWORD \
                        --upload-file target/your-artifact.jar \
                        ${NEXUS_URL}your/group/id/your-artifact-id/1.0.0/your-artifact-id-1.0.0.jar
                    """
                }
            }
        }

        stage('Deploy to Tomcat') {
            steps {
                // Using credentials for Tomcat
                withCredentials([usernamePassword(credentialsId: TOMCAT_CREDENTIALS_ID, usernameVariable: 'TOMCAT_USERNAME', passwordVariable: 'TOMCAT_PASSWORD')]) {
                    sh """
                        curl -v --user $TOMCAT_USERNAME:$TOMCAT_PASSWORD \
                        --upload-file target/your-artifact.war \
                        ${TOMCAT_URL}/deploy?path=/yourapp
                    """
                }
            }
        }
    }

    post {
        always {
            junit 'target/surefire-reports/*.xml'
            cleanWs()
        }
    }
}
