pipeline {
    agent any

    tools {
        maven 'Maven 3.6.3' // Specify the Maven tool name configured in Jenkins
    }

    environment {
        SONAR_LOGIN = 'sqa_e2e0dae9d7a2c5d12338834474b5932dee3c2805'
        NEXUS_USERNAME = 'admin'
        NEXUS_PASSWORD = 'admin123'
        TOMCAT_SERVER = 'http://3.110.204.118:8080/'
        TOMCAT_USER = 'saipurandhar'
        TOMCAT_PASSWORD = 'admin123'
    }

    stages {
        stage('Checkout') {
            steps {
                // Checkout the code from the development branch
                git url: 'https://github.com/your-repo.git', branch: 'development'
            }
        }

        stage('Build') {
            steps {
                // Run Maven build
                sh 'mvn clean install'
            }
        }

        stage('SonarQube Analysis') {
            steps {
                // Run SonarQube analysis
                sh 'mvn sonar:sonar -Dsonar.login=$SONAR_LOGIN'
            }
        }

        stage('Deploy to Nexus') {
            steps {
                // Deploy artifacts to Nexus
                sh '''
                mvn deploy -DaltDeploymentRepository=nexus::default::http://your-nexus-server:8081/repository/maven-releases/ \
                  -Dnexus.username=$NEXUS_USERNAME \
                  -Dnexus.password=$NEXUS_PASSWORD
                '''
            }
        }

        stage('Deploy to Tomcat') {
            steps {
                // Deploy WAR to Tomcat
                sh '''
                curl -u $TOMCAT_USER:$TOMCAT_PASSWORD \
                --upload-file target/your-app.war \
                "http://$TOMCAT_SERVER:8080/manager/text/deploy?path=/your-app&update=true"
                '''
            }
        }
    }
}
